### ISSUE TITLE
Cannot start phx server

### ISSUE THREAD

**Issue by bnymn** [dogweather/phoenix-docker-compose#4]
Hello,

I am not able to start the phx server. This is what I see in the logs:

```
phx_1  | ** (Mix) Could not find a Mix.Project, please ensure you are running Mix in a directory with a mix.exs file
```

I think it is trying to run the **run.sh** before binding the volume.

**Comment by bnymn** [comment]
In the second attempt to start the docker, I got the following in logs:

```
phx_1  | ** (File.Error) could not read file "/app/config/config.exs": no such file or directory
phx_1  |     (elixir 1.10.1) lib/file.ex:353: File.read!/1
phx_1  |     (elixir 1.10.1) lib/code.ex:863: Code.eval_file/2
phx_1  |     (elixir 1.10.1) lib/config.ex:219: Config.__eval__!/2
phx_1  |     (mix 1.10.1) lib/mix/tasks/loadconfig.ex:38: Mix.Tasks.Loadconfig.load/1
phx_1  |     (mix 1.10.1) lib/mix/tasks/loadconfig.ex:28: Mix.Tasks.Loadconfig.run/1
phx_1  |     (mix 1.10.1) lib/mix/task.ex:330: Mix.Task.run_task/3
phx_1  |     (mix 1.10.1) lib/mix/cli.ex:81: Mix.CLI.run_task/2
```

**Comment by bnymn** [comment]
I can see that the mix.exs file is corrupted somehow.

```
root@ed8efee07183:/app# ls -al
ls: cannot access 'mix.exs': No such file or directory
total 4
drwxrwxrwx 1 root root 4096 Feb 24  2020 .
drwxr-xr-x 1 root root 4096 Feb 23 10:28 ..
-rwxr-xr-x 1 root root   57 Feb 23 06:20 .env
-rwxr-xr-x 1 root root  159 Feb 23 07:41 .formatter.exs
-rwxr-xr-x 1 root root  803 Feb 23 08:34 .gitignore
drwxrwxrwx 1 root root    0 Feb 23 06:36 .ssh
-rwxr-xr-x 1 root root 1080 Feb 23 10:18 Dockerfile
-rwxr-xr-x 1 root root  655 Feb 23 07:41 README.md
drwxrwxrwx 1 root root    0 Feb 23 07:41 config
-rwxr-xr-x 1 root root  630 Feb 24  2020 docker-compose.yml
drwxrwxrwx 1 root root    0 Feb 23 07:41 lib
-????????? ? ?    ?       ?            ? mix.exs
-rwxr-xr-x 1 root root 5845 Feb 23 07:50 mix.lock
drwxrwxrwx 1 root root    0 Feb 23 07:41 priv
-rwxr-xr-x 1 root root 1094 Feb 24  2020 run.sh
drwxrwxrwx 1 root root    0 Feb 23 07:41 test
```

**Comment by bnymn** [comment]
Ok, I have managed to make it work. I have deleted all images, and all containers, and then restarted the Docker.

I think one of the snapshots are corrupted somehow.
